language: node_js
node_js:
- '10'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
- yarn lerna:bootstrap
script:
- yarn test
- yarn build
deploy:
  provider: script
  script: yarn lerna:publish
  skip_cleanup: true
  email: fra.pirrotta@gmail.com
  on:
    node: '10'
    tags: true
env:
  global:
    secure: pNnc8shPG0R0Da4T6LBKgDNx+mMQCQ4kcT7QXTRcgkL0j5kYdskpwqn8bcdNl5QLKLkeQ2Xuk+4t9njE1kXhLEZBYy2c+gS8ovRW0899JL5IwdyensX9xOdF/2F75gNT5X0SEFuPYVBL9S+qATF4zsaFo33HzK3TIeoTnINkLITIQ5W8x4aa0uMLJjo8/giX2b8TVzEOQ98OKqJ7UcWaRMTXXPbe0EBravmWAu3G0e5p/7ZmoZw5JO9hdYMZMm/btPVYK3z2bw7DLC+1eJo08EKWSoeU4KtZ7cJZVVtpOTc2Gnmg/ZajFg48SAE2kEEs9mXPTx2gWJzTTy+1FN9tj5GaraiIQ/6wlar03GZu3v7Mo9bN+KtU1jY1SSDYwe0x93ylsIbUvM+fuL9gFHu0vm6jZopCH+eyauXN6u/ihyKbs3STUO83j3ImhyyT+RMZgOdLdGuSFymqgozLIt34fimyiG9uo3y0cJPJoGmwUdY13fgWINi4mveEAVFzSAHx4XZrxLmxTJpQ8W4+UfeE8HJhpny54Xs8ZiI5mo1ovY/KTp0qcq0WYpFZzYVwZ6nw7RcthT3zSAXQShiWoaDlhiZfyZPkuVjUVfR0wMckYjr6hux7/VMtwS/Nt1H+9fKg1wF6bXLsZwbyQoK0bDqOE4AdrFO7SKe21vt/V8AkWVc=
